In [1]:
!pip install pandas-profiling

Collecting pandas-profiling
  Downloading pandas_profiling-3.2.0-py2.py3-none-any.whl.metadata (21 kB)
Collecting joblib~=1.1.0 (from pandas-profiling)
  Downloading joblib-1.1.1-py2.py3-none-any.whl.metadata (5.2 kB)
Requirement already satisfied: scipy>=1.4.1 in /opt/anaconda3/envs/sparshML/lib/python3.13/site-packages (from pandas-profiling) (1.17.1)
Requirement already satisfied: pandas!=1.0.0,!=1.0.1,!=1.0.2,!=1.1.0,>=0.25.3 in /opt/anaconda3/envs/sparshML/lib/python3.13/site-packages (from pandas-profiling) (3.0.3)
Requirement already satisfied: matplotlib>=3.2.0 in /opt/anaconda3/envs/sparshML/lib/python3.13/site-packages (from pandas-profiling) (3.11.0)
Collecting pydantic>=1.8.1 (from pandas-profiling)
  Downloading pydantic-2.13.4-py3-none-any.whl.metadata (109 kB)
Requirement already satisfied: PyYAML>=5.0.0 in /opt/anaconda3/envs/sparshML/lib/python3.13/site-packages (from pandas-profiling) (6.0.3)
Requirement already satisfied: jinja2>=2.11.1 in /opt/anaconda3/envs/sparshML/lib/python3.13/site-packages (from pandas-profiling) (3.1.6)
Collecting markupsafe~=2.1.1 (from pandas-profiling)
  Downloading MarkupSafe-2.1.5.tar.gz (19 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting visions==0.7.4 (from visions[type_image_path]==0.7.4->pandas-profiling)
  Downloading visions-0.7.4-py3-none-any.whl.metadata (5.9 kB)
Requirement already satisfied: numpy>=1.16.0 in /opt/anaconda3/envs/sparshML/lib/python3.13/site-packages (from pandas-profiling) (2.4.6)
Collecting htmlmin>=0.1.12 (from pandas-profiling)
  Downloading htmlmin-0.1.12.tar.gz (19 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [27 lines of output]
      Traceback (most recent call last):
        File "/opt/anaconda3/envs/sparshML/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 389, in <module>
          main()
          ~~~~^^
        File "/opt/anaconda3/envs/sparshML/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 373, in main
          json_out["return_val"] = hook(**hook_input["kwargs"])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/anaconda3/envs/sparshML/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 143, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/qm/jcdvmprs4834d492btkf492h0000gn/T/pip-build-env-rlod7ly5/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 333, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/qm/jcdvmprs4834d492btkf492h0000gn/T/pip-build-env-rlod7ly5/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 301, in _get_build_requires
          self.run_setup()
          ~~~~~~~~~~~~~~^^
        File "/private/var/folders/qm/jcdvmprs4834d492btkf492h0000gn/T/pip-build-env-rlod7ly5/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 520, in run_setup
          super().run_setup(setup_script=setup_script)
          ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/qm/jcdvmprs4834d492btkf492h0000gn/T/pip-build-env-rlod7ly5/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 317, in run_setup
          exec(code, locals())
          ~~~~^^^^^^^^^^^^^^^^
        File "<string>", line 4, in <module>
        File "/private/var/folders/qm/jcdvmprs4834d492btkf492h0000gn/T/pip-install-cpljthty/htmlmin_2ce7190db9ea4669b17b96d8fe08abf1/htmlmin/__init__.py", line 28, in <module>
          from .main import minify, Minifier
        File "/private/var/folders/qm/jcdvmprs4834d492btkf492h0000gn/T/pip-install-cpljthty/htmlmin_2ce7190db9ea4669b17b96d8fe08abf1/htmlmin/main.py", line 28, in <module>
          import cgi
      ModuleNotFoundError: No module named 'cgi'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
ERROR: Failed to build 'htmlmin' when getting requirements to build wheel

In [2]:
import pandas as pd
df=pd.read_csv("tested.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [4]:
from pandas_profiling import ProfileReport
prof=ProfileReport(df)
prof.to_file(output_file='output.html')

ModuleNotFoundError: No module named 'pandas_profiling'

In [5]:
!pip uninstall pandas-profiling -y
!pip install ydata-profiling

WARNING: Skipping pandas-profiling as it is not installed.
Collecting ydata-profiling
  Downloading ydata_profiling-4.18.4-py2.py3-none-any.whl.metadata (23 kB)
Collecting scipy<1.17,>=1.8 (from ydata-profiling)
  Downloading scipy-1.16.3-cp313-cp313-macosx_14_0_arm64.whl.metadata (62 kB)
Collecting pandas!=1.4.0,<3.0,>1.5 (from ydata-profiling)
  Downloading pandas-2.3.3-cp313-cp313-macosx_11_0_arm64.whl.metadata (91 kB)
Collecting matplotlib<=3.10,>=3.5 (from ydata-profiling)
  Downloading matplotlib-3.10.0-cp313-cp313-macosx_11_0_arm64.whl.metadata (11 kB)
Collecting pydantic<3,>=2 (from ydata-profiling)
  Using cached pydantic-2.13.4-py3-none-any.whl.metadata (109 kB)
Requirement already satisfied: PyYAML<6.1,>=6.0.3 in /opt/anaconda3/envs/sparshML/lib/python3.13/site-packages (from ydata-profiling) (6.0.3)
Requirement already satisfied: jinja2<3.2,>=3.1.6 in /opt/anaconda3/envs/sparshML/lib/python3.13/site-packages (from ydata-profiling) (3.1.6)
Collecting visions<0.8.2,>=0.7.5 (from visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling)
  Downloading visions-0.8.1-py3-none-any.whl.metadata (11 kB)
Collecting numpy<2.4,>=1.22 (from ydata-profiling)
  Downloading numpy-2.3.5-cp313-cp313-macosx_14_0_arm64.whl.metadata (62 kB)
Collecting minify-html>=0.15.0 (from ydata-profiling)
  Downloading minify_html-0.18.1-cp313-cp313-macosx_11_0_arm64.whl.metadata (18 kB)
Collecting filetype>=1.0.0 (from ydata-profiling)
  Downloading filetype-1.2.0-py2.py3-none-any.whl.metadata (6.5 kB)
Collecting phik<0.13,>=0.12.5 (from ydata-profiling)
  Downloading phik-0.12.5-cp313-cp313-macosx_11_0_arm64.whl.metadata (5.6 kB)
Requirement already satisfied: requests<3,>=2.32.0 in /opt/anaconda3/envs/sparshML/lib/python3.13/site-packages (from ydata-profiling) (2.34.2)
Collecting tqdm<5,>=4.66.3 (from ydata-profiling)
  Downloading tqdm-4.68.3-py3-none-any.whl.metadata (57 kB)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in /opt/anaconda3/envs/sparshML/lib/python3.13/site-packages (from ydata-profiling) (0.13.2)
Collecting multimethod<2,>=1.4 (from ydata-profiling)
  Downloading multimethod-1.12-py3-none-any.whl.metadata (9.6 kB)
Collecting statsmodels<1,>=0.13.2 (from ydata-profiling)
  Downloading statsmodels-0.14.6-cp313-cp313-macosx_11_0_arm64.whl.metadata (9.5 kB)
Collecting typeguard<5,>=4 (from ydata-profiling)
  Downloading typeguard-4.5.2-py3-none-any.whl.metadata (3.8 kB)
Collecting imagehash==4.3.2 (from ydata-profiling)
  Downloading ImageHash-4.3.2-py2.py3-none-any.whl.metadata (8.4 kB)
Collecting wordcloud>=1.9.4 (from ydata-profiling)
  Downloading wordcloud-1.9.6-cp313-cp313-macosx_11_0_arm64.whl.metadata (3.4 kB)
Collecting dacite<2,>=1.9 (from ydata-profiling)
  Downloading dacite-1.9.2-py3-none-any.whl.metadata (17 kB)
Collecting numba<0.63,>=0.60 (from ydata-profiling)
  Downloading numba-0.62.1-cp313-cp313-macosx_12_0_arm64.whl.metadata (2.8 kB)
Collecting PyWavelets (from imagehash==4.3.2->ydata-profiling)
  Downloading pywavelets-1.9.0-cp313-cp313-macosx_11_0_arm64.whl.metadata (7.6 kB)
Requirement already satisfied: pillow in /opt/anaconda3/envs/sparshML/lib/python3.13/site-packages (from imagehash==4.3.2->ydata-profiling) (12.2.0)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/anaconda3/envs/sparshML/lib/python3.13/site-packages (from jinja2<3.2,>=3.1.6->ydata-profiling) (3.0.2)
Requirement already satisfied: contourpy>=1.0.1 in /opt/anaconda3/envs/sparshML/lib/python3.13/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /opt/anaconda3/envs/sparshML/lib/python3.13/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /opt/anaconda3/envs/sparshML/lib/python3.13/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /opt/anaconda3/envs/sparshML/lib/python3.13/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /opt/anaconda3/envs/sparshML/lib/python3.13/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (26.0)
Requirement already satisfied: pyparsing>=2.3.1 in /opt/anaconda3/envs/sparshML/lib/python3.13/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /opt/anaconda3/envs/sparshML/lib/python3.13/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (2.9.0.post0)
Collecting llvmlite<0.46,>=0.45.0dev0 (from numba<0.63,>=0.60->ydata-profiling)
  Downloading llvmlite-0.45.1-cp313-cp313-macosx_12_0_arm64.whl.metadata (4.8 kB)
Collecting pytz>=2020.1 (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling)
  Downloading pytz-2026.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling)
  Downloading tzdata-2026.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: joblib>=0.14.1 in /opt/anaconda3/envs/sparshML/lib/python3.13/site-packages (from phik<0.13,>=0.12.5->ydata-profiling) (1.5.3)
Collecting annotated-types>=0.6.0 (from pydantic<3,>=2->ydata-profiling)
  Downloading annotated_types-0.7.0-py3-none-any.whl.metadata (15 kB)
Collecting pydantic-core==2.46.4 (from pydantic<3,>=2->ydata-profiling)
  Downloading pydantic_core-2.46.4-cp313-cp313-macosx_11_0_arm64.whl.metadata (6.6 kB)
Requirement already satisfied: typing-extensions>=4.14.1 in /opt/anaconda3/envs/sparshML/lib/python3.13/site-packages (from pydantic<3,>=2->ydata-profiling) (4.15.0)
Collecting typing-inspection>=0.4.2 (from pydantic<3,>=2->ydata-profiling)
  Downloading typing_inspection-0.4.2-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/anaconda3/envs/sparshML/lib/python3.13/site-packages (from requests<3,>=2.32.0->ydata-profiling) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/envs/sparshML/lib/python3.13/site-packages (from requests<3,>=2.32.0->ydata-profiling) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in /opt/anaconda3/envs/sparshML/lib/python3.13/site-packages (from requests<3,>=2.32.0->ydata-profiling) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in /opt/anaconda3/envs/sparshML/lib/python3.13/site-packages (from requests<3,>=2.32.0->ydata-profiling) (2026.5.20)
Collecting patsy>=0.5.6 (from statsmodels<1,>=0.13.2->ydata-profiling)
  Downloading patsy-1.0.2-py2.py3-none-any.whl.metadata (3.6 kB)
Requirement already satisfied: attrs>=19.3.0 in /opt/anaconda3/envs/sparshML/lib/python3.13/site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (26.1.0)
Collecting networkx>=2.4 (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling)
  Downloading networkx-3.6.1-py3-none-any.whl.metadata (6.8 kB)
Collecting puremagic (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling)
  Downloading puremagic-2.2.0-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/envs/sparshML/lib/python3.13/site-packages (from python-dateutil>=2.7->matplotlib<=3.10,>=3.5->ydata-profiling) (1.17.0)
Downloading ydata_profiling-4.18.4-py2.py3-none-any.whl (400 kB)
Downloading ImageHash-4.3.2-py2.py3-none-any.whl (296 kB)
Downloading dacite-1.9.2-py3-none-any.whl (16 kB)
Downloading matplotlib-3.10.0-cp313-cp313-macosx_11_0_arm64.whl (8.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.0/8.0 MB 468.5 kB/s  0:00:17m0:00:0100:01
Downloading multimethod-1.12-py3-none-any.whl (10 kB)
Downloading numba-0.62.1-cp313-cp313-macosx_12_0_arm64.whl (2.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.7/2.7 MB 276.6 kB/s  0:00:09 eta 0:00:02
Downloading llvmlite-0.45.1-cp313-cp313-macosx_12_0_arm64.whl (37.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 37.3/37.3 MB 273.3 kB/s  0:05:18m0:00:0200:05
Downloading numpy-2.3.5-cp313-cp313-macosx_14_0_arm64.whl (5.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.1/5.1 MB 96.0 kB/s  0:00:45m0:00:0200:05m
Downloading pandas-2.3.3-cp313-cp313-macosx_11_0_arm64.whl (10.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.7/10.7 MB 241.0 kB/s  0:00:39m0:00:0100:02
Downloading phik-0.12.5-cp313-cp313-macosx_11_0_arm64.whl (666 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 666.9/666.9 kB 75.4 kB/s  0:00:06 eta 0:00:02
Downloading pydantic-2.13.4-py3-none-any.whl (472 kB)
Downloading pydantic_core-2.46.4-cp313-cp313-macosx_11_0_arm64.whl (2.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 98.7 kB/s  0:00:25 eta 0:00:02
Downloading scipy-1.16.3-cp313-cp313-macosx_14_0_arm64.whl (20.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.9/20.9 MB 115.4 kB/s  0:01:57m0:00:0200:07
Downloading statsmodels-0.14.6-cp313-cp313-macosx_11_0_arm64.whl (10.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.0/10.0 MB 63.4 kB/s  0:02:55eta 0:00:06m
Downloading tqdm-4.68.3-py3-none-any.whl (78 kB)
Downloading typeguard-4.5.2-py3-none-any.whl (36 kB)
Downloading visions-0.8.1-py3-none-any.whl (105 kB)
Downloading annotated_types-0.7.0-py3-none-any.whl (13 kB)
Downloading filetype-1.2.0-py2.py3-none-any.whl (19 kB)
Downloading minify_html-0.18.1-cp313-cp313-macosx_11_0_arm64.whl (2.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.8/2.8 MB 53.6 kB/s  0:00:49 eta 0:00:05m
Downloading networkx-3.6.1-py3-none-any.whl (2.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 97.7 kB/s  0:00:22 eta 0:00:03
Downloading patsy-1.0.2-py2.py3-none-any.whl (233 kB)
Downloading pytz-2026.2-py2.py3-none-any.whl (510 kB)
Downloading typing_inspection-0.4.2-py3-none-any.whl (14 kB)
Downloading tzdata-2026.2-py2.py3-none-any.whl (349 kB)
Downloading wordcloud-1.9.6-cp313-cp313-macosx_11_0_arm64.whl (168 kB)
Downloading puremagic-2.2.0-py3-none-any.whl (71 kB)
Downloading pywavelets-1.9.0-cp313-cp313-macosx_11_0_arm64.whl (4.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.3/4.3 MB 154.0 kB/s  0:00:27m0:00:0100:03
Installing collected packages: pytz, minify-html, filetype, tzdata, typing-inspection, typeguard, tqdm, pydantic-core, puremagic, numpy, networkx, multimethod, llvmlite, dacite, annotated-types, scipy, PyWavelets, pydantic, patsy, pandas, numba, visions, statsmodels, matplotlib, imagehash, wordcloud, phik, ydata-profiling
  Attempting uninstall: numpy0m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  3/28 [tzdata]
    Found existing installation: numpy 2.4.6━━━━━━━━━━━━━━━━━━  3/28 [tzdata]
    Uninstalling numpy-2.4.6:╸━━━━━━━━━━━━━━━━━━━━━━━━━━━  9/28 [numpy]
      Successfully uninstalled numpy-2.4.6━━━━━━━━━━━━━━━━━━━━  9/28 [numpy]
  Attempting uninstall: scipy╺━━━━━━━━━━━━━━━━━━━━━━ 12/28 [llvmlite]
    Found existing installation: scipy 1.17.1━━━━━━━━━━━━━━━━━ 12/28 [llvmlite]
    Uninstalling scipy-1.17.1:[0m╺━━━━━━━━━━━━━━━━━━ 15/28 [scipy]
      Successfully uninstalled scipy-1.17.1m━━━━━━━━━━━━━━━━━━ 15/28 [scipy]
  Attempting uninstall: pandas━━╺━━━━━━━━━━━━━━━ 17/28 [pydantic]s]
    Found existing installation: pandas 3.0.30m━━━━━━━━━━━━━━━ 17/28 [pydantic]
    Uninstalling pandas-3.0.3:━━━━━╺━━━━━━━━━━━━ 19/28 [pandas]
      Successfully uninstalled pandas-3.0.30m━━━━━━━━━━━━ 19/28 [pandas]
  Attempting uninstall: matplotlib━━━━━╺━━━━━━━━ 22/28 [statsmodels]
    Found existing installation: matplotlib 3.11.0[90m━━━━━━━━ 22/28 [statsmodels]
    Uninstalling matplotlib-3.11.0:━━━━━╸━━━━━━━ 23/28 [matplotlib]
      Successfully uninstalled matplotlib-3.11.0m╸━━━━━━━ 23/28 [matplotlib]
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 28/28 [ydata-profiling] [ydata-profiling]
Successfully installed PyWavelets-1.9.0 annotated-types-0.7.0 dacite-1.9.2 filetype-1.2.0 imagehash-4.3.2 llvmlite-0.45.1 matplotlib-3.10.0 minify-html-0.18.1 multimethod-1.12 networkx-3.6.1 numba-0.62.1 numpy-2.3.5 pandas-2.3.3 patsy-1.0.2 phik-0.12.5 puremagic-2.2.0 pydantic-2.13.4 pydantic-core-2.46.4 pytz-2026.2 scipy-1.16.3 statsmodels-0.14.6 tqdm-4.68.3 typeguard-4.5.2 typing-inspection-0.4.2 tzdata-2026.2 visions-0.8.1 wordcloud-1.9.6 ydata-profiling-4.18.4

In [6]:
from pandas_profiling import ProfileReport
prof=ProfileReport(df)
prof.to_file(output_file='output.html')

ModuleNotFoundError: No module named 'pkg_resources'

In [7]:
!pip install --upgrade setuptools

Requirement already satisfied: setuptools in /opt/anaconda3/envs/sparshML/lib/python3.13/site-packages (82.0.1)

In [8]:
from ydata_profiling import ProfileReport

profile = ProfileReport(df)
profile.to_file("output.html")

ModuleNotFoundError: No module named 'pkg_resources'

In [9]:
import sys
print(sys.version)

3.13.13 | packaged by Anaconda, Inc. | (main, Apr 14 2026, 06:14:06) [Clang 20.1.8 ]

In [10]:
from ydata_profiling import ProfileReport

profile = ProfileReport(df)
profile.to_file("output.html")

ModuleNotFoundError: No module named 'pkg_resources'

In [11]:
!pip show setuptools

Name: setuptools
Version: 82.0.1
Summary: Most extensible Python build backend with support for C/C++ extension modules
Home-page:
Author:
Author-email: Python Packaging Authority <distutils-sig@python.org>
License-Expression: MIT
Location: /opt/anaconda3/envs/sparshML/lib/python3.13/site-packages
Requires:
Required-by: jupyterlab

In [12]:
import pkg_resources

ModuleNotFoundError: No module named 'pkg_resources'

In [13]:
!pip uninstall setuptools -y
!pip install setuptools==75.8.0

Found existing installation: setuptools 82.0.1
Uninstalling setuptools-82.0.1:
  Successfully uninstalled setuptools-82.0.1
Error processing line 1 of /opt/anaconda3/envs/sparshML/lib/python3.13/site-packages/distutils-precedence.pth:

  Traceback (most recent call last):
    File "<frozen site>", line 207, in addpackage
    File "<string>", line 1, in <module>
  ModuleNotFoundError: No module named '_distutils_hack'

Remainder of file ignored
Collecting setuptools==75.8.0
  Downloading setuptools-75.8.0-py3-none-any.whl.metadata (6.7 kB)
Downloading setuptools-75.8.0-py3-none-any.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 3.0 MB/s  0:00:00 eta 0:00:01
Installing collected packages: setuptools
Successfully installed setuptools-75.8.0

In [1]:
import pkg_resources
print("pkg_resources loaded successfully")

pkg_resources loaded successfully

/var/folders/qm/jcdvmprs4834d492btkf492h0000gn/T/ipykernel_92202/404892036.py:1: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources

In [3]:
from ydata_profiling import ProfileReport
print("Imported successfully")

Imported successfully

In [4]:
from ydata_profiling import ProfileReport

profile = ProfileReport(df)
profile.to_file("output.html")

NameError: name 'df' is not defined

In [5]:
import pandas as pd
df=pd.read_csv("tested.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [6]:
from ydata_profiling import ProfileReport

profile = ProfileReport(df)
profile.to_file("output.html")

Summarize dataset:  47%|████▋     | 8/17 [00:00<00:00, 79.08it/s, Describe variable: Embarked]
100%|██████████| 12/12 [00:00<00:00, 1178.40it/s]00:00, 88.53it/s, Describe variable: Embarked]
Summarize dataset: 100%|██████████| 47/47 [00:01<00:00, 31.03it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:01<00:00,  1.22s/it]
Render HTML: 100%|██████████| 1/1 [00:00<00:00,  1.10it/s]
Export report to file: 100%|██████████| 1/1 [00:00<00:00, 319.30it/s]

In [8]:
import pandas as pd
data=pd.read_csv("placement-dataset.csv")
data.head()

          city  cgpa     iq  placement
0     New York   6.8  123.0          1
1  Los Angeles   5.9  106.0          0
2      Chicago   NaN  121.0          0
3     New York   7.4  132.0          1
4  Los Angeles   5.8  142.0          0

In [9]:
from ydata_profiling import ProfileReport
prof=ProfileReport(data)
prof.to_file("placementoutput.html")

Summarize dataset:   0%|          | 0/9 [00:00<?, ?it/s, Describe variable: placement]
Task was destroyed but it is pending!
task: <Task pending name='Task-130' coro=<_async_in_context.<locals>.run_in_context() done, defined at /opt/anaconda3/envs/sparshML/lib/python3.13/site-packages/ipykernel/utils.py:57> wait_for=<Task pending name='Task-131' coro=<Kernel.shell_main() running at /opt/anaconda3/envs/sparshML/lib/python3.13/site-packages/ipykernel/kernelbase.py:597> cb=[Task.task_wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at /opt/anaconda3/envs/sparshML/lib/python3.13/site-packages/zmq/eventloop/zmqstream.py:563]>
Summarize dataset:  33%|███▎      | 3/9 [00:00<00:00, 25.97it/s, Describe variable: placement]/opt/anaconda3/envs/sparshML/lib/python3.13/site-packages/pandas/core/groupby/ops.py:126: RuntimeWarning: coroutine 'Kernel.shell_main' was never awaited
  def __init__(self, kind: str, how: str, has_dropped_na: bool) -> None:
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Task was destroyed but it is pending!
task: <Task pending name='Task-131' coro=<Kernel.shell_main() running at /opt/anaconda3/envs/sparshML/lib/python3.13/site-packages/ipykernel/kernelbase.py:597> cb=[Task.task_wakeup()]>
Task was destroyed but it is pending!
task: <Task pending name='Task-148' coro=<_async_in_context.<locals>.run_in_context() done, defined at /opt/anaconda3/envs/sparshML/lib/python3.13/site-packages/ipykernel/utils.py:57> wait_for=<Task pending name='Task-149' coro=<Kernel.shell_main() running at /opt/anaconda3/envs/sparshML/lib/python3.13/site-packages/ipykernel/kernelbase.py:597> cb=[Task.task_wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at /opt/anaconda3/envs/sparshML/lib/python3.13/site-packages/zmq/eventloop/zmqstream.py:563]>
Task was destroyed but it is pending!
task: <Task pending name='Task-149' coro=<Kernel.shell_main() running at /opt/anaconda3/envs/sparshML/lib/python3.13/site-packages/ipykernel/kernelbase.py:597> cb=[Task.task_wakeup()]>
Task was destroyed but it is pending!
task: <Task pending name='Task-184' coro=<_async_in_context.<locals>.run_in_context() done, defined at /opt/anaconda3/envs/sparshML/lib/python3.13/site-packages/ipykernel/utils.py:57> wait_for=<Task pending name='Task-185' coro=<Kernel.shell_main() running at /opt/anaconda3/envs/sparshML/lib/python3.13/site-packages/ipykernel/kernelbase.py:597> cb=[Task.task_wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at /opt/anaconda3/envs/sparshML/lib/python3.13/site-packages/zmq/eventloop/zmqstream.py:563]>
Task was destroyed but it is pending!
task: <Task pending name='Task-185' coro=<Kernel.shell_main() running at /opt/anaconda3/envs/sparshML/lib/python3.13/site-packages/ipykernel/kernelbase.py:597> cb=[Task.task_wakeup()]>
100%|██████████| 4/4 [00:00<00:00, 106.73it/s]
Summarize dataset: 100%|██████████| 18/18 [00:00<00:00, 38.78it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:00<00:00,  3.62it/s]
Render HTML: 100%|██████████| 1/1 [00:00<00:00, 24.71it/s]
Export report to file: 100%|██████████| 1/1 [00:00<00:00, 1084.92it/s]