In [103]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import MinMaxScaler
from sklearn.feature_selection import SelectKBest,chi2 
from sklearn.tree import DecisionTreeClassifier
from sklearn.pipeline import Pipeline,make_pipeline

In [104]:
df=pd.read_csv("train.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [105]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [106]:
df.drop(columns=['PassengerId','Name','Ticket','Cabin'],inplace=True)

In [107]:
df.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [118]:
x_train,x_test,y_train,y_test=train_test_split(df.drop(columns='Survived'),df['Survived'],test_size=0.2)

In [119]:
x_train

     Pclass     Sex   Age  SibSp  Parch      Fare Embarked
753       3    male  23.0      0      0    7.8958        S
594       2    male  37.0      1      0   26.0000        S
698       1    male  49.0      1      1  110.8833        C
427       2  female  19.0      0      0   26.0000        S
577       1  female  39.0      1      0   55.9000        S
..      ...     ...   ...    ...    ...       ...      ...
852       3  female   9.0      1      1   15.2458        C
124       1    male  54.0      0      1   77.2875        S
342       2    male  28.0      0      0   13.0000        S
590       3    male  35.0      0      0    7.1250        S
49        3  female  18.0      1      0   17.8000        S

[712 rows x 7 columns]

In [120]:
y_train

753    0
594    0
698    0
427    1
577    1
      ..
852    0
124    0
342    0
590    0
49     0
Name: Survived, Length: 712, dtype: int64

In [121]:
#for removing the null values using imputer
trf1=ColumnTransformer(
    [('impute_age',SimpleImputer(),[2]),
     ('impute_embarked',SimpleImputer(strategy='most_frequent'),[6])],remainder="passthrough")

In [122]:
#applying One Hot Encoding
trf2=ColumnTransformer(
    [('ohe_sex_embarked',OneHotEncoder(sparse_output=False,handle_unknown="ignore"),[1,6])],remainder='passthrough')

In [123]:
#Scaling
trf3=ColumnTransformer(
    [('scale',MinMaxScaler(),slice(0,10))])

In [124]:
#Feature Selection
trf4=SelectKBest(score_func=chi2,k=5)

In [125]:
#train the model
trf5=DecisionTreeClassifier()

CREATE PIPELINE

In [126]:
pipe=Pipeline([
    ('trf1',trf1),
    ('trf2',trf2),
    ('trf3',trf3),
    ('trf4',trf4),
    ('trf5',trf5)])

In [127]:
pipe.fit(x_train,y_train)

Pipeline(steps=[('trf1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('impute_age', SimpleImputer(),
                                                  [2]),
                                                 ('impute_embarked',
                                                  SimpleImputer(strategy='most_frequent'),
                                                  [6])])),
                ('trf2',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('ohe_sex_embarked',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  [1, 6])])),
                ('trf3',
                 ColumnTransformer(transformers=[('scale', MinMaxScaler(),
                                                  slice(0, 10, None))])),
                ('trf4',
                 SelectKBest(k=5, score_func=<function chi2 at 0x11f622980>)),
                ('trf5', DecisionTreeClassifier())])

Pipeline V/S make_pipeline

In [ ]:
#alternate syntax
pipe=make_pipeline(tr1,trf2,trf3,trf4,trf5)
#train 
pipe.fit(x_train,y_train)

Exporting Pipeline

In [128]:
#export
import pickle
pickle.dump(pipe,open('pipe.pkl','wb'))

In [129]:
!git status

On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   OneHotEncoding(feature trans)using column transformer.ipynb

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	.ipynb_checkpoints/pipeline(ml)-checkpoint.ipynb
	pipe.pkl
	pipeline(ml).ipynb
	train.csv

no changes added to commit (use "git add" and/or "git commit -a")

In [130]:
!git add .

In [132]:
!git commit -m "pipeline"

[main ef3f12b] pipeline
 Committer: stuti pangeni <stutipangeni@sparsh-macbook.local>
Your name and email address were configured automatically based
on your username and hostname. Please check that they are accurate.
You can suppress this message by setting them explicitly:

    git config --global user.name "Your Name"
    git config --global user.email you@example.com

After doing this, you may fix the identity used for this commit with:

    git commit --amend --reset-author

 5 files changed, 7587 insertions(+), 2 deletions(-)
 create mode 100644 .ipynb_checkpoints/pipeline(ml)-checkpoint.ipynb
 create mode 100644 pipe.pkl
 create mode 100644 pipeline(ml).ipynb
 create mode 100644 train.csv

In [133]:
!git push origin main

Enumerating objects: 10, done.
Counting objects: 100% (10/10), done.
Delta compression using up to 8 threads
Compressing objects: 100% (7/7), done.
Writing objects: 100% (7/7), 61.33 KiB | 12.27 MiB/s, done.
Total 7 (delta 3), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (3/3), completed with 3 local objects.
To https://github.com/killersparsh123/100_days_of_ml.git
   9950bd4..ef3f12b  main -> main